[package]
name = "axe-fx-midi"
version = "0.1.0"
authors = ["Bradley J. Spaulding <brad.spaulding@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "axe_fx_midi"
crate-type = ["staticlib", "cdylib"]
