# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/clojure:boot-2.7.1

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.boot" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: boot testing test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.boot" }}
