(ns axe-fx-midi.npm
  (:require-macros [axe-fx-midi.macros :refer [defexport]])
  (:require [axe-fx-midi.core :as axefx]
            [axe-fx-midi.models :as models]))

(defexport parseMessage (fn [msg] (clj->js (axefx/parse-message (js->clj msg)))))
(defexport storeInPreset axefx/store-in-preset)
(defexport setTargetBlock axefx/set-target-block)
(defexport getPresetEditedStatus axefx/get-preset-edited-status)
(defexport getCPUUsage axefx/get-cpu-usage)
(defexport setBlockY axefx/set-block-y)
(defexport setBlockX axefx/set-block-x)
(defexport getBlockXY axefx/get-block-xy)
(defexport midiLooperStatusDisable axefx/midi-looper-status-disable)
(defexport midiLooperStatusEnable axefx/midi-looper-status-enable)
(defexport setModifierValue axefx/set-modifier-value)
(defexport getModifierValue axefx/get-modifier-value)
(defexport setTypedBlockParameterValue axefx/set-typed-block-parameter-value)
(defexport setTempo axefx/set-tempo)
(defexport setBlockParameterValue axefx/set-block-parameter-value)
(defexport getBlockParameterValue axefx/get-block-parameter-value)
(defexport getBlockParametersList axefx/get-block-parameters-list)
(defexport getGridLayoutAndRouting axefx/get-grid-layout-and-routing)
(defexport setSceneNumber axefx/set-scene-number)
(defexport getPresetBlocksFlags axefx/get-preset-blocks-flags)
(defexport toggleMetronome axefx/metronome-toggle)
(defexport toggleTuner axefx/tuner-toggle)
(defexport getMidiChannel axefx/get-midi-channel)
(defexport disconnectFromController axefx/disconnect-from-controller)
(defexport getFirmwareVersion axefx/get-firmware-version)
(defexport setPresetName axefx/set-preset-name)
(defexport getPresetName axefx/get-preset-name)
(defexport setPresetNumber axefx/set-preset-number)
(defexport getPresetNumber axefx/get-preset-number)
(defexport models (clj->js models/models))
